services:
  api: 
    build: .
    container_name: api
    ports:
      - "8080:8080"
    depends_on:
      - db
  db:
    image: postgres:13.22-alpine3.22
    container_name: blog-postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - blog-data:/var/lib/postgresql/data
      - ./scripts/postgres:/docker-entrypoint-initdb.d/
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB" ]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s

volumes:
  blog-data: